import { Pool, MaintenanceLog, User } from '@/types/database';

export const mockUsers: User[] = [
  {
    id: 'u-1',
    name: 'Diretoria Executiva JHostonTec',
    email: 'diretoria@jhostontec.com.br',
    phone: '5511988887777',
    role: 'DIRETORIA_JH',
    created_at: new Date().toISOString(),
  },
  {
    id: 'u-2',
    name: 'Carlos Oliveira (Auditor Técnico JHoston)',
    email: 'carlos.auditor@jhostontec.com.br',
    phone: '5511999990001',
    role: 'TECNICO_JH',
    created_at: new Date().toISOString(),
  },
  {
    id: 'u-3',
    name: 'Resort Terravista (Gerência Geral)',
    email: 'gerencia@resorterravista.com.br',
    phone: '5573999992222',
    role: 'GERENCIA_CLI',
    created_at: new Date().toISOString(),
  },
  {
    id: 'u-4',
    name: 'João Tratador (Piscineiro Credenciado)',
    email: 'joao.piscineiro@gmail.com',
    phone: '5573988883333',
    cpf: '123.456.789-00',
    role: 'PISCINEIRO',
    created_at: new Date().toISOString(),
  },
];

export const mockPools: Pool[] = [
  {
    id: 'p-1',
    name: 'Piscina Olímpica Aquecida - Resort Terravista',
    owner_id: 'u-3',
    facility_type: 'RESORT',
    volume_m3: 350.0,
    pump_flow_m3_h: 45.0,
    gps_lat: -16.425123,
    gps_lng: -39.062451,
    application_date: '2026-09-01',
    status: 'NORMAL',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-2',
    name: 'Piscina de Areia Monolítica - Hotel Fasano',
    owner_id: 'u-3',
    facility_type: 'HOTEL',
    volume_m3: 180.0,
    pump_flow_m3_h: 25.0,
    gps_lat: -16.441123,
    gps_lng: -39.071234,
    application_date: '2026-09-20',
    status: 'RED_ZONE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'p-3',
    name: 'Piscina Residencial Privativa - Alphaville',
    owner_id: 'u-3',
    facility_type: 'PESSOA_FISICA',
    volume_m3: 65.0,
    pump_flow_m3_h: 12.0,
    gps_lat: -16.431234,
    gps_lng: -39.055678,
    application_date: '2026-09-28',
    status: 'SUBMERGED_CURE',
    created_at: new Date().toISOString(),
  },
];

export const mockMaintenanceLogs: MaintenanceLog[] = [
  {
    id: 'log-1',
    pool_id: 'p-2',
    maintainer_id: 'u-4',
    log_date: new Date(Date.now() - 3600000).toISOString(),
    ph: 6.8,
    chlorine_ppm: 1.2,
    alkalinity_ppm: 60,
    calcium_hardness_ppm: 180,
    brushed_surface: true,
    backwashed_filter: false,
    acid_product_used: false,
    weather_condition_at_log: 'Chuva Leve',
    liability_accepted: true,
    is_audit_flagged: true,
    flag_reason: '🚨 Detectamos pH de risco (6.8). Risco de Corrosão imediata no revestimento monolítico.',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    calculation_memory: {
      formula: '[Dose Padrão (34.00g/m³)] × [Volume (180m³)]',
      volume_m3: 180,
      dose_used: 34,
      total_debited: 6120,
      unit: 'g',
    },
  },
  {
    id: 'log-2',
    pool_id: 'p-1',
    maintainer_id: 'u-4',
    log_date: new Date(Date.now() - 7200000).toISOString(),
    ph: 7.4,
    chlorine_ppm: 2.2,
    alkalinity_ppm: 100,
    calcium_hardness_ppm: 220,
    brushed_surface: true,
    backwashed_filter: true,
    acid_product_used: false,
    weather_condition_at_log: 'Ensolarado',
    liability_accepted: true,
    is_audit_flagged: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
];
